package leetcode;
/* Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
 * Method: (1) sum of chars (2) hashmap (naive)
 */
public class lc_389_findTheDifference {
	public char findTheDifference(String s, String t) {
        int sums = 0;
        int sumt = 0;
        
        for (int i = 0; i < s.length(); i++){
            sums += (int)(s.charAt(i));
        }
        
        for (int j = 0; j < t.length(); j++){
            sumt += (int)(t.charAt(j));
        }
        
        int diff = sumt - sums;
        return (char)diff;
    }
	
}
